# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb796f1266547a84bb62b7a0c52e6e0b4d19123b33c62a636b646ddab0a8fe77aa2490bcd54e63fac243afb53de8994a5d61b76180c06b664a2e9719c8418c0e

test:
  secret_key_base: f6db8a4897d35820b0190ca795973a36b4e7bab875d76bc982c9dfb1f5b2f96d70a5cac0fa4e2b8a0eb02a6e68e6734abec49d3826aa7a6973269743d0915b58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
